=== domchevskayaA/subnet-docs/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "bittensor_id": {
      "type": "string",
      "description": "The Bittensor identifier for the subnet"
    },
    "letter": {
      "type": "string",
      "description": "The letter of the subnet"
    },
    "name": {
      "type": "string",
      "description": "The display name of the subnet"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "The category of the subnet"
      }
    },
    "github": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "GitHub repository URL associated with the subnet"
      },
      "description": "List of GitHub repositories"
    },
    "hw_requirements": {
      "type": "string",
      "description": "URL or description of hardware requirements"
    },
    "image_url": {
      "type": "string",
      "description": "URL to the subnet's image"
    },
    "description": {
      "type": "string",
      "description": "Detailed description file reference or content"
    },
    "bittensor_discord_id": {
      "type": "string",
      "description": "Discord channel ID associated with the subnet in the Bittensor Discord server"
    },
    "team": {
      "type": "string",
      "description": "Name of the team or organization behind the subnet"
    },
    "summary": {
      "type": "string",
      "description": "Brief description of the subnet's purpose and functionality"
    },
    "websites": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string",
            "enum": [
              "substack",
              "tao.bot",
              "whitepaper",
              "miner dashboard",
              "huggingface",
              "website",
              "twitter",
              "roadmap",
              "wandb logger",
              "market analysis",
              "blog",
              "chrome extension",
              "discord",
              "omega focus",
              "dashboard",
              "leaderboard",
              "application",
              "tplx_publication_link"
            ],
            "description": "Label or type of the website link"
          },
          "url": {
            "type": "string",
            "description": "URL of the website"
          }
        },
        "required": ["label", "url"]
      },
      "description": "List of associated websites and links"
    }
  },
  "required": [
    "bittensor_id",
    "letter",
    "name",
    "github",
    "hw_requirements",
    "image_url",
    "description",
    "bittensor_discord_id",
    "team",
    "summary",
    "websites"
  ]
}

=== domchevskayaA/subnet-docs/data/81/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "",
  "name": "Patrol (TAO.com)",
  "github": ["https://github.com/tao-dot-com/patrol_subnet"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/81/v1.png",
  "description": "description.html",
  "bittensor_discord_id": "1354089114189955102",
  "team": "TAO.com",
  "summary": "Secure crypto funds and provide all holders peace of mind, wherever they are.",
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/tao_dot_com"
    },
    {
      "label": "discord",
      "url": "https://discord.gg/Q74Vm5G8"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/11/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "lambda",
  "letter": "Î»",
  "name": "Dippy Roleplay",
  "github": ["https://github.com/impel-intelligence/dippy-bittensor-subnet"],
  "hw_requirements": "https://github.com/impel-intelligence/dippy-bittensor-subnet/blob/main/min_compute.yml",
  "image_url": "https://github.com/impel-intelligence/dippy-bittensor-subnet/raw/main/assests/banner.png",
  "description": "description.html",
  "bittensor_discord_id": "1232378968187867147",
  "team": "Impel",
  "categories": ["Model Development"],
  "summary": "The Dippy Roleplay subnet on Bittensor aims to create the world's best open-source roleplay LLM by leveraging the collective efforts of the open-source community.",
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/dippy_ai"
    },
    {
      "label": "application",
      "url": "https://bittensor.dippy.ai/play"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/28/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "×“",
  "name": "LOL",
  "github": [""],
  "hw_requirements": "",
  "image_url": "https://assets.backprop.finance/subnet-logos/28/v1.jpg",
  "description": "",
  "bittensor_discord_id": "1343950080465698836",
  "team": "",
  "summary": "",
  "websites": []
}

=== domchevskayaA/subnet-docs/data/8/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "proprietary_trading_network",
  "letter": "Î¸",
  "name": "Proprietary Trading Network",
  "github": ["https://github.com/taoshidev/proprietary-trading-network"],
  "hw_requirements": "",
  "image_url": "",
  "description": "description.html",
  "bittensor_discord_id": "1162384774170677318",
  "team": "",
  "summary": "The Proprietary Trading Network incentivizes the contribution of profitable trading strategies across various financial markets. Contributors who provide the best trading signals receive the highest rewards, attracting skilled traders, data scientists, and machine learning teams to compete.",
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/taoshiio"
    },
    {
      "label": "website",
      "url": "https://www.taoshi.io/"
    },
    {
      "label": "dashboard",
      "url": "https://dashboard.taoshi.io/"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/73/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "Ùƒ",
  "name": "",
  "github": [],
  "hw_requirements": "",
  "image_url": "https://assets.backprop.finance/subnet-logos/default.png",
  "description": "",
  "bittensor_discord_id": "1349123085877379112",
  "team": "",
  "summary": "",
  "websites": []
}

=== domchevskayaA/subnet-docs/data/90/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "",
  "name": "brain",
  "github": ["https://github.com/frkrueger/bittensor-brain-subnet"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/default.png",
  "description": "description.html",
  "bittensor_discord_id": "",
  "team": "",
  "summary": "A Bittensor subnet focused on validating prediction market results. This subnet leverages open-source verification methods to determine the truth value of statements with confidence intervals.",
  "websites": []
}

=== domchevskayaA/subnet-docs/data/97/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "",
  "name": "Flamewire",
  "github": ["https://github.com/unitone-labs/FlameWire"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/97/v1.png",
  "description": "description.html",
  "bittensor_discord_id": "",
  "team": "UnitOne Labs",
  "summary": "FlameWire powers Ethereum, Bittensor, SUI, and more through a decentralized RPC/API infrastructure with global coverage, preserving crypto's core values decentralization, availability, and censorship resistance.",
  "websites": [
    {
      "label": "website",
      "url": "https://flamewire.io/"
    },
    {
      "label": "twitter",
      "url": "https://x.com/FlameWire_SN"
    },
    {
      "label": "twitter",
      "url": "https://x.com/UnitOne_Labs"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/15/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "omicron",
  "letter": "Î¿",
  "name": "De-Val",
  "github": ["https://github.com/deval-core/De-Val"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/15/v1.jpg",
  "description": "description.html",
  "bittensor_discord_id": "1272557411948957697",
  "team": "De-Val",
  "summary": "de_val sets the new benchmark for AI excellence, offering a decentralized evaluation platform designed to enhance LLM performance with unmatched quality. With de_val, you can rigorously test your AI models throughout the ML ops pipeline (offline testing, A/B testing, and continuous monitoring), measuring hallucinations, misattributions, relevancy, and summarization comprehensiveness, so you can understand your outputs at scale and deploy with confidence.",
  "categories": ["Model Development"],
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/deval_ai"
    },
    {
      "label": "website",
      "url": "https://www.de-val.ai/"
    },
    {
      "label": "whitepaper",
      "url": "https://www.de-val.ai/pitch_deck"
    }
  ]
}
