=== domchevskayaA/subnet-docs/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "bittensor_id": {
      "type": "string",
      "description": "The Bittensor identifier for the subnet"
    },
    "letter": {
      "type": "string",
      "description": "The letter of the subnet"
    },
    "name": {
      "type": "string",
      "description": "The display name of the subnet"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "The category of the subnet"
      }
    },
    "github": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "GitHub repository URL associated with the subnet"
      },
      "description": "List of GitHub repositories"
    },
    "hw_requirements": {
      "type": "string",
      "description": "URL or description of hardware requirements"
    },
    "image_url": {
      "type": "string",
      "description": "URL to the subnet's image"
    },
    "description": {
      "type": "string",
      "description": "Detailed description file reference or content"
    },
    "bittensor_discord_id": {
      "type": "string",
      "description": "Discord channel ID associated with the subnet in the Bittensor Discord server"
    },
    "team": {
      "type": "string",
      "description": "Name of the team or organization behind the subnet"
    },
    "summary": {
      "type": "string",
      "description": "Brief description of the subnet's purpose and functionality"
    },
    "websites": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string",
            "enum": [
              "substack",
              "tao.bot",
              "whitepaper",
              "miner dashboard",
              "huggingface",
              "website",
              "twitter",
              "roadmap",
              "wandb logger",
              "market analysis",
              "blog",
              "chrome extension",
              "discord",
              "omega focus",
              "dashboard",
              "leaderboard",
              "application",
              "tplx_publication_link"
            ],
            "description": "Label or type of the website link"
          },
          "url": {
            "type": "string",
            "description": "URL of the website"
          }
        },
        "required": ["label", "url"]
      },
      "description": "List of associated websites and links"
    }
  },
  "required": [
    "bittensor_id",
    "letter",
    "name",
    "github",
    "hw_requirements",
    "image_url",
    "description",
    "bittensor_discord_id",
    "team",
    "summary",
    "websites"
  ]
}

=== domchevskayaA/subnet-docs/data/71/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "ŸÅ",
  "name": "",
  "github": [],
  "hw_requirements": "",
  "image_url": "https://assets.backprop.finance/subnet-logos/default.png",
  "description": "",
  "bittensor_discord_id": "1349121405903573114",
  "team": "",
  "summary": "",
  "websites": []
}

=== domchevskayaA/subnet-docs/data/42/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "masa",
  "letter": "×¡",
  "name": "Masa",
  "github": ["https://github.com/masa-finance"],
  "hw_requirements": "",
  "image_url": "",
  "description": "description.html",
  "bittensor_discord_id": "1275149537547391058",
  "team": "Masa",
  "summary": "Masa focuses on decentralized data scraping, offering an alternative to traditional centralized services like BrightData and Apify.",
  "websites": [
    {
      "label": "website",
      "url": "https://developers.masa.ai/docs/masa-subnet/welcome"
    },
    {
      "label": "twitter",
      "url": "https://x.com/getmasafi"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/35/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "logicnet",
  "letter": "×š",
  "name": "LogicNet",
  "github": ["https://github.com/LogicNet-Subnet/LogicNet"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/35/v1.png",
  "description": "description.html",
  "bittensor_discord_id": "1204855126045753434",
  "team": "Logic Net",
  "summary": "LogicNet focuses on developing open-source mathematics and detailed data analysis models.",
  "categories": ["Model Development"],
  "websites": [
    {
      "label": "website",
      "url": "https://tonylvh.notion.site/LogicNet_SN35-1b44e52d308f47e7983af25bff6df90e"
    },
    {
      "label": "dashboard",
      "url": "https://logicnet.streamlit.app/"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/37/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "fine_tuning",
  "letter": "×œ",
  "name": "Fine-Tuning",
  "github": ["https://github.com/macrocosm-os/finetuning"],
  "hw_requirements": "",
  "image_url": "",
  "description": "description.html",
  "bittensor_discord_id": "1253448873305964626",
  "team": "Macrocosmos",
  "summary": "Fine-Tuning is focused on the production of fine-tuned models. Contributors are rewarded based on their models' head-to-head scores, with evaluations based on a continuous stream of synthetic data generated by the top LLMs. The evaluation data setup helps reduce the potential of the benchmark being gamed.",
  "categories": ["Model Development", "Macrocosmos"],
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/MacrocosmosAI"
    },
    {
      "label": "website",
      "url": "https://www.macrocosmos.ai/sn37"
    },
    {
      "label": "dashboard",
      "url": "https://www.macrocosmos.ai/sn37/dashboard"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/88/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "ы",
  "name": "Sταking",
  "github": ["https://github.com/mobiusfund/staking"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/88/v1.webp",
  "description": "description.html",
  "bittensor_discord_id": "1358854051634221328",
  "team": "",
  "summary": "Optimizing Staking Strategies",
  "websites": [
    {
      "label": "dashboard",
      "url": "https://stakingalpha.com"
    },
    {
      "label": "twitter",
      "url": "https://x.com/StakingAlpha88"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/75/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "Ù…",
  "name": "Hippius",
  "github": [
    "https://github.com/thenervelab/hippius-cli",
    "https://github.com/thenervelab/hippius-network-mesh-config"
  ],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/75/v1.jpg",
  "description": "",
  "bittensor_discord_id": "1349124437752152075",
  "team": "",
  "summary": "",
  "categories": ["Storage"],
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/hippius_subnet"
    },
    {
      "label": "website",
      "url": "https://hippius.com"
    },
    {
      "label": "discord",
      "url": "https://discord.hippius.com"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/6/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "infinite_games",
  "letter": "Î¶",
  "name": "Infinite Games",
  "github": ["https://github.com/amedeo-gigaver/infinite_games/tree/main"],
  "hw_requirements": "",
  "image_url": "",
  "description": "description.html",
  "bittensor_discord_id": "1209554949449457705",
  "team": "",
  "summary": "Infinite Games incentivizes the prediction of future events by rewarding contributors based on the accuracy and speed of their model's forecasts. The subnet currently focuses on binary future events listed on Polymarket and Azuro.",
  "categories": ["Prediction Market"],
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/Playinfgames"
    },
    {
      "label": "website",
      "url": "https://www.infinitegam.es/"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/31/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "",
  "name": "NullUntilBoot",
  "github": ["https://github.com/NeuralNexusII/NullUntilBoot"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/default.png",
  "description": "",
  "bittensor_discord_id": "1361421560988041267",
  "team": "",
  "summary": "",
  "categories": [],
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/NullUntilBoot"
    }
  ]
}
