=== domchevskayaA/subnet-docs/schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "type": "object",
  "properties": {
    "bittensor_id": {
      "type": "string",
      "description": "The Bittensor identifier for the subnet"
    },
    "letter": {
      "type": "string",
      "description": "The letter of the subnet"
    },
    "name": {
      "type": "string",
      "description": "The display name of the subnet"
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "The category of the subnet"
      }
    },
    "github": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "GitHub repository URL associated with the subnet"
      },
      "description": "List of GitHub repositories"
    },
    "hw_requirements": {
      "type": "string",
      "description": "URL or description of hardware requirements"
    },
    "image_url": {
      "type": "string",
      "description": "URL to the subnet's image"
    },
    "description": {
      "type": "string",
      "description": "Detailed description file reference or content"
    },
    "bittensor_discord_id": {
      "type": "string",
      "description": "Discord channel ID associated with the subnet in the Bittensor Discord server"
    },
    "team": {
      "type": "string",
      "description": "Name of the team or organization behind the subnet"
    },
    "summary": {
      "type": "string",
      "description": "Brief description of the subnet's purpose and functionality"
    },
    "websites": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "label": {
            "type": "string",
            "enum": [
              "substack",
              "tao.bot",
              "whitepaper",
              "miner dashboard",
              "huggingface",
              "website",
              "twitter",
              "roadmap",
              "wandb logger",
              "market analysis",
              "blog",
              "chrome extension",
              "discord",
              "omega focus",
              "dashboard",
              "leaderboard",
              "application",
              "tplx_publication_link"
            ],
            "description": "Label or type of the website link"
          },
          "url": {
            "type": "string",
            "description": "URL of the website"
          }
        },
        "required": ["label", "url"]
      },
      "description": "List of associated websites and links"
    }
  },
  "required": [
    "bittensor_id",
    "letter",
    "name",
    "github",
    "hw_requirements",
    "image_url",
    "description",
    "bittensor_discord_id",
    "team",
    "summary",
    "websites"
  ]
}

=== domchevskayaA/subnet-docs/data/114/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "",
  "name": "Eclipse",
  "github": [],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/114/v1.png",
  "description": "",
  "bittensor_discord_id": "",
  "team": "",
  "summary": "",
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/Bittensor_SN114"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/55/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "Ø«",
  "name": "Precog",
  "github": ["https://github.com/coinmetrics/precog"],
  "hw_requirements": "",
  "image_url": "",
  "description": "",
  "bittensor_discord_id": "1320766712508977192",
  "team": "Coin Metric",
  "summary": "The Precog Subnet will serve as an arena to identify the analysts with the best strategies and information to anticipate Bitcoin price movements, and recruit them to share their insight with the broader community.",
  "categories": ["Prediction Market", "Financial Trading"],
  "websites": [
    {
      "label": "website",
      "url": "http://coinmetrics.io/precog"
    },
    {
      "label": "twitter",
      "url": "https://x.com/CM_Precog"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/39/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "edge_maxxing",
  "letter": "×ž",
  "name": "EdgeMaxxing",
  "github": ["https://github.com/womboai/edge-optimization-subnet"],
  "hw_requirements": "",
  "image_url": "",
  "description": "description.html",
  "bittensor_discord_id": "1241046233800507482",
  "team": "Wombo",
  "summary": "EdgeMaxxing is focused on optimizing AI models for consumer devices, starting with Stable Diffusion XL on the NVIDIA GeForce RTX 4090. By optimizing popular models for edge devices, the subnet aims to transform idle computing resources into valuable contributors to decentralized inference networks.",
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/WOMBO"
    },
    {
      "label": "website",
      "url": "https://www.w.ai/"
    },
    {
      "label": "dashboard",
      "url": "https://huggingface.co/spaces/wombo/edge-maxxing-dashboard"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/16/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "bitads",
  "letter": "Ï€",
  "name": "BitAds",
  "github": ["https://github.com/eseckft/BitAds.ai"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/16/v1.jpg",
  "description": "description.html",
  "bittensor_discord_id": "1189234502669697064",
  "team": "",
  "summary": "BitAds is focused on reshaping online advertising with its Conversion Tracking system, which ensures advertisers pay only for successful sales. Contributors are rewarded based on the sales generated through their unique links.",
  "categories": ["Marketing"],
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/BitAds_AI"
    },
    {
      "label": "website",
      "url": "https://bitads.ai/"
    },
    {
      "label": "whitepaper",
      "url": "https://bitads.ai/whitepaper"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/67/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "",
  "name": "",
  "github": [],
  "hw_requirements": "",
  "image_url": "https://assets.backprop.finance/subnet-logos/default.png",
  "description": "",
  "bittensor_discord_id": "",
  "team": "",
  "summary": "",
  "websites": []
}

=== domchevskayaA/subnet-docs/data/85/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "áš¨",
  "name": "vidaio",
  "github": ["https://github.com/vidaio-subnet/vidaio-subnet"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/85/v1.jpg",
  "description": "",
  "bittensor_discord_id": "",
  "team": "",
  "summary": "",
  "websites": []
}

=== domchevskayaA/subnet-docs/data/12/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "horde",
  "letter": "Âµ",
  "name": "Horde",
  "github": ["https://github.com/backend-developers-ltd/ComputeHorde"],
  "hw_requirements": "",
  "image_url": "",
  "description": "",
  "bittensor_discord_id": "1201941624243109888",
  "team": "",
  "summary": "Horde is a cloud platform dedicated to networkless GPU-equipped servers. It implements hardware classes to establish a free market that optimizes for cost-effectiveness over merely the strongest hardware.",
  "websites": [
    {
      "label": "dashboard",
      "url": "https://grafana.bactensor.io/d/b2d70a9d-e838-402c-8e2a-5476fac8de1c/sn12-compute-power?orgId=1&from=now-2d&to=now"
    },
    {
      "label": "application",
      "url": "https://facilitator.computehorde.io/"
    }
  ]
}

=== domchevskayaA/subnet-docs/data/93/subnet.json
{
  "$schema": "../../schema.json",
  "bittensor_id": "",
  "letter": "",
  "name": "Bitcast",
  "github": ["https://github.com/bitcast-network/bitcast"],
  "hw_requirements": "",
  "image_url": "https://backprop.finance/assets/subnet-logos/93/v1.jpg",
  "description": "",
  "bittensor_discord_id": "1362489640841380045",
  "team": "",
  "summary": "The Decentralized Creators Economy Powered by Bittensor",
  "websites": [
    {
      "label": "twitter",
      "url": "https://x.com/Bitcast_network"
    },
    {
      "label": "website",
      "url": "https://www.bitcast.network"
    },
    {
      "label": "whitepaper",
      "url": "https://www.bitcast.network/white-paper"
    },
    {
      "label": "dashboard",
      "url": "https://dashboard.bitcast.network/"
    },
    {
      "label": "wandb logger",
      "url": "https://wandb.ai/bitcast_network/bitcast_vali_logs"
    }
  ]
}
